from __future__ import annotations

import re


THEME_MODES = {"light", "dark"}
AUTO_SYNC_INTERVAL_MS = 1_500
EVENT_SYNC_DELAY_MS = 120
EMULATOR_POLL_INTERVAL_MS = 850
EMULATOR_POLL_IMMEDIATE_INTERVAL_MS = 120
EMULATOR_STATE_CONFIRMATION_COUNT = 1
EMULATOR_STATUS_REFRESH_DEBOUNCE_MS = 60
EMULATOR_STATUS_REFRESH_MIN_GAP_MS = 180
LIVE_RICH_PRESENCE_MAX_AGE_SECONDS = 20 * 60
LIVE_RECENT_PLAYED_MAX_AGE_SECONDS = 20 * 60
LIVE_RECENT_PLAYED_FALLBACK_MAX_AGE_SECONDS = 20
EVENT_SYNC_LIVE_MIN_GAP_MS = 3_000
EVENT_SYNC_IDLE_MIN_GAP_MS = 18_000
CURRENT_GAME_LOADING_OVERLAY_MAX_MS = 25_000
SAVED_WINDOW_GEOMETRY_RETRY_DELAY_MS = 160
SAVED_WINDOW_GEOMETRY_RETRY_COUNT = 3
IMAGE_FETCH_TIMEOUT_SECONDS = 3
MAX_ACHIEVEMENT_BADGE_FETCH = 4
PROBE_LOG_PREFIX = "PROBE"
PROBE_LOG_REPEAT_MIN_INTERVAL_SECONDS = 4.0
STATUS_TIMER_REFRESH_INTERVAL_MS = 120
NEXT_ACHIEVEMENT_BADGE_MAX_SIZE = 124
ACHIEVEMENT_NA_VALUE = "N/A"
EMULATOR_STATUS_INACTIVE = "Inactif"
EMULATOR_STATUS_EMULATOR_LOADED = "Émulateur chargé"
EMULATOR_STATUS_GAME_LOADED = "Jeu chargé"
ACHIEVEMENT_SCROLL_INTERVAL_MS = 75
ACHIEVEMENT_ORDER_NORMAL = "normal"
ACHIEVEMENT_ORDER_EASY_TO_HARD = "easy_to_hard"
ACHIEVEMENT_ORDER_HARD_TO_EASY = "hard_to_easy"
ACHIEVEMENT_ORDER_CYCLE = (
    ACHIEVEMENT_ORDER_NORMAL,
    ACHIEVEMENT_ORDER_EASY_TO_HARD,
    ACHIEVEMENT_ORDER_HARD_TO_EASY,
)
ACHIEVEMENT_ORDER_LABELS = {
    ACHIEVEMENT_ORDER_NORMAL: "Ordre: Normal",
    ACHIEVEMENT_ORDER_EASY_TO_HARD: "Ordre: Facile -> Difficile",
    ACHIEVEMENT_ORDER_HARD_TO_EASY: "Ordre: Difficile -> Facile",
}
ACHIEVEMENT_CLICK_PREVIEW_MS = 10_000
ACHIEVEMENT_CLICK_PREVIEW_UNLOCKED_MS = 15_000
ACHIEVEMENT_CLICK_DOUBLE_WINDOW_SECONDS = 1.2
NOTEBOOK_TAB_SECTION_GAP = 10
MAIN_TAB_CURRENT = "current"
MAIN_TAB_GAMES = "games"
MAIN_TAB_RECENT = "recent"
MAIN_TAB_ORDER = (MAIN_TAB_CURRENT, MAIN_TAB_GAMES, MAIN_TAB_RECENT)
MAIN_TAB_LABELS = {
    MAIN_TAB_CURRENT: "Jeu en cours",
    MAIN_TAB_GAMES: "Progression par jeu",
    MAIN_TAB_RECENT: "Succès récents",
}
MAIN_TAB_MAINTENANCE_KEYS = {MAIN_TAB_GAMES, MAIN_TAB_RECENT}
WINDOW_GEOMETRY_RE = re.compile(r"^\d+x\d+[+-]\d+[+-]\d+$")
DWMWA_WINDOW_CORNER_PREFERENCE = 33
DWMWCP_ROUND_SMALL = 3
UNIFIED_CORNER_RADIUS = 10
DEFAULT_WIDGET_CORNER_RADIUS = UNIFIED_CORNER_RADIUS
COVER_IMAGE_CORNER_RADIUS = UNIFIED_CORNER_RADIUS
BADGE_IMAGE_CORNER_RADIUS = UNIFIED_CORNER_RADIUS
ACHIEVEMENT_IMAGE_CORNER_RADIUS = UNIFIED_CORNER_RADIUS
IMAGE_ROUNDING_INSET = 1
